# Generated by Django 3.0.8 on 2020-07-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ammo', models.FloatField()),
                ('mag', models.FloatField()),
                ('ext_mag', models.FloatField()),
                ('fire_rate', models.FloatField()),
                ('damage', models.FloatField()),
                ('bullet_speed', models.FloatField()),
                ('rload', models.FloatField()),
                ('shot_range', models.FloatField()),
                ('scoped_spread', models.FloatField()),
                ('dps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='dmr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ammo', models.FloatField()),
                ('mag', models.FloatField()),
                ('ext_mag', models.FloatField()),
                ('fire_rate', models.FloatField()),
                ('damage', models.FloatField()),
                ('bullet_speed', models.FloatField()),
                ('rload', models.FloatField()),
                ('shot_range', models.FloatField()),
                ('scoped_spread', models.FloatField()),
                ('dps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='lmg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ammo', models.FloatField()),
                ('mag', models.FloatField()),
                ('ext_mag', models.FloatField()),
                ('fire_rate', models.FloatField()),
                ('damage', models.FloatField()),
                ('bullet_speed', models.FloatField()),
                ('rload', models.FloatField()),
                ('shot_range', models.FloatField()),
                ('scoped_spread', models.FloatField()),
                ('dps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ammo', models.CharField(max_length=60)),
                ('mag', models.FloatField()),
                ('ext_mag', models.FloatField()),
                ('fire_rate', models.FloatField()),
                ('damage', models.FloatField()),
                ('bullet_speed', models.FloatField()),
                ('rload', models.FloatField()),
                ('shot_range', models.FloatField()),
                ('scoped_spread', models.FloatField()),
                ('dps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='pistol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ammo', models.FloatField()),
                ('mag', models.FloatField()),
                ('ext_mag', models.FloatField()),
                ('fire_rate', models.FloatField()),
                ('damage', models.FloatField()),
                ('bullet_speed', models.FloatField()),
                ('rload', models.FloatField()),
                ('shot_range', models.FloatField()),
                ('scoped_spread', models.FloatField()),
                ('dps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='shotgun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ammo', models.FloatField()),
                ('mag', models.FloatField()),
                ('ext_mag', models.FloatField()),
                ('fire_rate', models.FloatField()),
                ('damage', models.FloatField()),
                ('bullet_speed', models.FloatField()),
                ('rload', models.FloatField()),
                ('shot_range', models.FloatField()),
                ('scoped_spread', models.FloatField()),
                ('dps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='smg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ammo', models.FloatField()),
                ('mag', models.FloatField()),
                ('ext_mag', models.FloatField()),
                ('fire_rate', models.FloatField()),
                ('damage', models.FloatField()),
                ('bullet_speed', models.FloatField()),
                ('rload', models.FloatField()),
                ('shot_range', models.FloatField()),
                ('scoped_spread', models.FloatField()),
                ('dps', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sniper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ammo', models.FloatField()),
                ('mag', models.FloatField()),
                ('ext_mag', models.FloatField()),
                ('fire_rate', models.FloatField()),
                ('damage', models.FloatField()),
                ('bullet_speed', models.FloatField()),
                ('rload', models.FloatField()),
                ('shot_range', models.FloatField()),
                ('scoped_spread', models.FloatField()),
                ('dps', models.FloatField()),
            ],
        ),
    ]
