# Generated by Django 3.0.8 on 2020-07-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_gun_guntype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gun',
        ),
        migrations.DeleteModel(
            name='Guntype',
        ),
    ]
